version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    volumes:
      - app_data:/usr/share/nginx/html/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "90:90"
    volumes:
      - app_data:/usr/share/nginx/html/app

volumes:
  app_data:
