# Usa la imagen oficial de Nginx
FROM nginx:latest

# Copia la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

#creo carpeta de aplicacion de angular
RUN mkdir -p /angularapp

# Da permisos de lectura y escritura a la carpeta /usr/share/nginx/html
RUN chmod -R 777 /angularapp

# Expone el puerto 90
EXPOSE 90

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
